Update run-rust script: allow overriding RUST_HOME and better error handling

diff --git a/run-rust b/run-rust
--- a/run-rust
+++ b/run-rust
@@ -1,20 +1,24 @@
 #!/bin/sh
-RUST_HOME=/home/install/rust
-# CARGO_HOME=/home/install/cargo
-PROG=$(basename $0)
 
+# RUST_HOME can be set on the command-line to use a custom installation
+if [ -z "$RUST_HOME" ]
+then
+    export RUST_HOME=/home/install/rust
+elif [ ! -x "$RUST_HOME/bin/rustc" ]
+then
+    echo "Not found: \$RUST_HOME/bin/rustc (expands to $RUST_HOME/bin/rustc)" >&2
+    exit 1
+fi
+
+PROG=$(basename $0)
 if [ ! -x "$RUST_HOME/bin/$PROG" ]; then
-    echo "Usage: make a symlink with one of the following names and execute that."
+    echo "Usage: make a symlink with one of the following names and execute that." >&2
     ls "$RUST_HOME/bin"
     exit 1
 fi
 
+export RUST_HOME
 export PATH="$PATH:$RUST_HOME/bin"
 export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$RUST_HOME/lib"
 
-if [ -x "$CARGO_HOME/bin/$PROG" ]; then
-    export PATH="$PATH:$CARGO_HOME/bin"
-    "$CARGO_HOME/bin/$PROG" "$@"
-else
-    "$RUST_HOME/bin/$PROG" "$@"
-fi
+"$RUST_HOME/bin/$PROG" "$@"
